### ISSUE TITLE
Configure for MagnePot Encoders

### ISSUE THREAD

**Issue by HiceS** [TeamMeanMachine/FRC2016#6]
# Enhancement for manipulator

We need to get the class from 2015 that transformed the magnepot values into a usable data-set because we will likely be using the MagnePots to tell distance with either the ShooterWheels (not likely) or the manipulations.

We might also need to reconfigure it because its not swerve use anymore.
Any suggestions?

[https://github.com/TeamMeanMachine/FRC2015/blob/master/src/org/usfirst/frc/team2471/robot/MagnePot.java](url)

**Comment by bobcroucher** [comment]
The magnepot encoders will be great for the intake arm or the obstacle
manipulator. They won't work for the shooter or anything that turns more
than one revolution.
